const bruxos = [
    {
        id: 1,
        nome: "Harry Potter",
        casa: "Grifinória",
        ano: 7,
        varinha: "Azevinho e pena de fênix, 28cm",
        mascote: "Coruja (Edwiges)",
        patrono: "Cervo",
        especialidade: "Sobreviver a Voldemort 😎",
    },
    {
        id: 2,
        nome: "Hermione Granger",
        casa: "Grifinória",
        ano: 7,
        varinha: "Videira e fibra de coração de dragão, 27cm",
        mascote: "Gato (Bichento)",
        patrono: "Lontra",
        especialidade: "Saber tudo de tudo",
    },
    {
        id: 3,
        nome: "Ron Weasley",
        casa: "Grifinória",
        ano: 7,
        varinha: "Salgueiro e crina de unicórnio, 35cm",
        mascote: "Rato (Perebas)",
        patrono: "Terrier Jack Russell",
        especialidade: "Xadrez Bruxo",
    },
    {
        id: 4,
        nome: "Draco Malfoy",
        casa: "Sonserina",
        ano: 7,
        varinha: "Espinheiro e crina de unicórnio, 25cm",
        mascote: "Coruja (não nomeada)",
        patrono: "Desconhecido",
        especialidade: "Ser irritante",
    },
    {
        id: 5,
        nome: "Luna Lovegood",
        casa: "Corvinal",
        ano: 6,
        varinha: "Madeira de cerejeira e núcleo desconhecido",
        mascote: "Nenhum",
        patrono: "Lebre",
        especialidade: "Ver criaturas imaginárias (ou não) 👻",
    },
    {
        id: 6,
        nome: "Neville Longbottom",
        casa: "Grifinória",
        ano: 7,
        varinha: "Cerejeira e pelo de unicórnio, 30cm",
        mascote: "Sapo (Trevor)",
        patrono: "Não conhecido",
        especialidade: "Herbologia avançada",

    },
    {
        id: 7,
        nome: "Cho Chang",
        casa: "Corvinal",
        ano: 7,
        varinha: "Salgueiro e fibra de coração de dragão, 23cm",
        mascote: "Coruja",
        patrono: "Cisne",
        especialidade: "Quadribol ", 
    },
    {
        id: 8,
        nome: "Cedrico Diggory",
        casa: "Lufa-Lufa",
        ano: 7,
        varinha: "Freixo e pelo de unicórnio, 32cm",
        mascote: "Nenhum",
        patrono: "Não Conhecido",
        especialidade: "Cavalheirismo", 
    },
    {
        id: 9,
        nome: "Bellatrix Lestrange",
        casa: "Sonserina",
        ano: 6,
        varinha: "Nogueira e fibra de coração de dragão, 32cm",
        mascote: "Nenhum",
        patrono: "Não Conhecido",
        especialidade: "Artes das Trevas", 
    },
    {
        id: 10,
        nome: "Minerva McGonagall",
        casa: "Grifinória",
        ano: 9,
        varinha: "Abeto e fibra de coração de dragão, 24cm",
        mascote: "Gato",
        patrono: "Gato",
        especialidade: "Transfiguração", 
    },
    {
        id: 11,
        nome: "Marius Flint",
        Casa: "Sonserina",
        Varinha: "Madeira de teixo com núcleo de fibra de dragão, 32 cm, flexível",
        Mascote: "Cobra (nomeada Serpente)",
        Patrono: "Cervo",
        Especialidade: "Magia das Trevas e Defesa contra as Artes das Trevas",
    },
    {
        id: 12,
        nome: "Fiona Greengrass",
        Casa: "Corvinal",
        Varinha: "Madeira de sabugueiro com núcleo de penas de fênix, 28 cm, rígida",
        Mascote: "Corvo (nomeado Eclipse)",
        Patrono: "Gato",
        Especialidade: "Transfiguração e Poções",
    },
    {
        id: 13,
        nome: "Aidan Hawke",
        Casa: "Lufa-Lufa",
        Varinha: "Madeira de carvalho com núcleo de cabelo de veela, 30 cm, flexível",
        Mascote: "Coelho (nomeado Fizz)",
        Patrono: "Águia",
        Especialidade: "Herbologia e Cuidado das Criaturas Mágicas",
    },
    {
        id: 14,
        nome: "Thaddeus Montague",
        Casa: "Grifinória",
        Varinha: "Madeira de carvalho negro com núcleo de osso de dragão, 31 cm, resistente",
        Mascote: "Gato preto (nomeado Sombra)",
        Patrono: "Leão",
        Especialidade: "Duelo e Feitiçaria de Combate",
    },
    {
        id: 15,
        nome: "Elowen Ashford",
        Casa: "Sonserina",
        Varinha: "Madeira de pinheiro com núcleo de corda de harpía, 29 cm, flexível",
        Mascote: "Pantera (nomeada Eclipse)",
        Patrono: "Lobo",
        Especialidade: "Magia de Ilusão e Encantamentos",
    }
];

export default {bruxos}